const mongoose = require("mongoose");

// 1. Schema define
const projectSchema = new mongoose.Schema({
  title: { type: String, required: true },
  description: String,
  techStack: String, // changed from [String] to String
  link: String
});

// 2. Model banao
const Project = mongoose.model("Project", projectSchema);

// 3. Sample data (seed ke liye)
const sampleProjects = [
  {
    title: "WonderLust",
    description: "A travel and stay booking platform inspired by Airbnb. Includes authentication, property listings, reviews, and MongoDB database integration.",
    techStack: "Node.js Express.js MongoDB EJS",
    link: "https://github.com/priyanshiKumari197/wonderlust-app"
  },
  {
    title: "Personal Portfolio",
    description: "A responsive personal portfolio website to showcase my projects, skills, and resume with contact form integration.",
    techStack: "React.js Tailwind CSS",
    link: "https://yourportfolio.com"
  },
  {
    title: "Real-Time Chat App",
    description: "A real-time chat application with private and group chat features using WebSockets, Socket.io, and MongoDB.",
    techStack: "Node.js Socket.io MongoDB",
    link: "https://github.com/username/chat-app"
  },
  {
    title: "Anime Search App",
    description: "A web application that allows users to search anime details using a public anime API with a clean UI.",
    techStack: "HTML CSS JavaScript",
    link: "https://priyanshikumari197.github.io/anime-search/"
  },
  {
    title: "Calculator App",
    description: "A simple and responsive calculator web application built with HTML, CSS, and vanilla JavaScript.",
    techStack: "HTML CSS JavaScript",
    link: "https://priyanshikumari197.github.io/Calculator/"
  },
  {
    title: "Simon Game",
    description: "A fun memory-based game where users repeat patterns generated by the system, built with JavaScript.",
    techStack: "HTML CSS JavaScript",
    link: "https://priyanshikumari197.github.io/Simon-game/"
  },
  {
    title: "Spotify Clone",
    description: "A frontend clone of Spotify with modern UI features, custom playlists, and responsive design.",
    techStack: "React.js CSS",
    link: "https://github.com/priyanshikumari197/spotify_clone"
  },
  {
    title: "To-Do List App",
    description: "A task management app where users can add, edit, and delete tasks, built with Node.js and MongoDB.",
    techStack: "Node.js Express.js MongoDB",
    link: "https://priyanshikumari197.github.io/To-Do-List/"
  }
];

// 4. Export dono
module.exports = { Project, sampleProjects };
